dev.galasa.uber.obr/pom.xml, galasa-bom/pom.xml
Signed-off-by: James Davies <jdavies47@hotmail.co.uk>
=> bumped selenium version

release.yaml
=> Release metadata file

javadocs/pom.template
=> correct encoding and do zip

javadocs/docker/Dockerfile
=> correct dockerfile

release.yaml
=> Up managers to cope with commons-io going to 2.9

release.yaml
=> New version for commons io

release.yaml
=> commons codec to 1.15

release.yaml
=> forgot to increase boot version

release.yaml
=> add the isolated indicator for all the managers

release.yaml
=> increase http to latest release

release.yaml
=> set http to be included automatically

release.yaml
=> increase version of snakeyaml

dev.galasa.uber.obr/pom.template, galasa-bom/pom.template
=> add signing

dev.galasa.uber.obr/pom.template, galasa-bom/pom.template, javadocs/pom.template, release.yaml
=> Increase to 17

release.yaml
Signed-off-by: David Roberts <david.roberts@uk.ibm.com>
=> Update to 0.17.0 for JVM server

release.yaml
Signed-off-by: David Roberts <david.roberts@uk.ibm.com>
=> zOS Manager to 0.17.0

release.yaml
Signed-off-by: David Roberts <david.roberts@uk.ibm.com>
=> Move CEDA Manager to 0.17.0

release.yaml
=> up runs api to 17

release.yaml
=> add the framework bundle to the bom as it was before

release.yaml
=> bump galasa,framework & couchdb to 17

release.yaml
Signed-off-by: Matthew Chivers <matthewchivers@outlook.com>
=> Bumped java manager(s) to version 0.17.0

release.yaml
=> Ecosystem 17

release.yaml
Required for @galasa-dev/managers#636.
Signed-off-by: Matthew Chivers <matthewchivers@outlook.com>
=> Bumped ipnetwork to 0.17.0

release.yaml
=> Web UI project added to release.yaml

release.yaml
=> RAS project bumped to 17 

release.yaml
=> boot to 17

release.yaml
=> etcd3 to 17

release.yaml
Signed-off-by: Will Yates <hobbit1983@gmail.com>
=> up HTTP manager

release.yaml
=> bump linux and openstack to 17

release.yaml
Signed-off-by: James Davies <jdavies47@hotmail.co.uk>
=> up level of IVT

dev.galasa.uber.obr/pom.template, galasa-bom/pom.template, release.yaml
=> Bump to 18

release.yaml
=> bump to 19

release.yaml
Signed-off-by: David Roberts <david.roberts@uk.ibm.com>
=> Add org.bouncycastle

release.yaml
=> bump to 20

docker/Dockerfile
=> copy galasabld to image so that it is easier to deploy to oss

tekton/pipe-javadoc-build.yaml, tekton/pipe-obr-repo-build.yaml, tekton/prun-main-javadoc-build.yaml, tekton/prun-main-obr-build.yaml, tekton/res-git-obr-main.yaml, tekton/res-git-obr-staging.yaml, tekton/task-javadoc-build.yaml, tekton/task-obr-repo-build.yaml
=> Tekton updates

docker/Dockerfile
=> default bld-binary

docker/Dockerfile
=> galasabld needs ca-certificates

release.yaml
=> add collections4 to mvp

release.yaml
=> Bump to 0.21.0

release.yaml
=> bump commons compress to 21

release.yaml
=> Bump GSON 2.9.0

release.yaml
Signed-off-by: James Davies <jdavies47@hotmail.co.uk>
=> bump to 0.22.0

release.yaml
=> Bump to 24

release.yaml
Signed-off-by: James Davies <jdavies47@hotmail.co.uk>
=> Removing JTA wrapper due to clash with JavaEE 1.8

release.yaml
Signed-off-by: Will Yates <hobbit1983@gmail.com>
=> add jta to obr

release.yaml
=> Upgrade apache velocity dep to fix security vulnerabilities

release.yaml
=> Add commons-lang3 to OBR

release.yaml
=> Add slf4j-api to uber obr

release.yaml
=> Upgrade version of slf4j

build-locally.sh
=> build obr locally with a script

release.yaml
For https://github.com/galasa-dev/projectmanagement/issues/1089
=> Bump http jetty to 4.2.2

release.yaml
=> Bump snakeyaml to 1.33

build-locally.sh
=> Update OBR location in build locally script

release.yaml
=> Bump development to version 0.26.0

release.yaml
Signed-off-by: Eamonn Mansour <47121388+eamansour@users.noreply.github.com>
=> Bump obr to 0.27.0

build-locally.sh
=> Bump version of framework and boot jar

release.yaml
Signed-off-by: Jade Carino <carino_jade@yahoo.co.uk>
=> Version bump development to 0.28.0

release.yaml
Signed-off-by: Jade Carino <carino_jade@yahoo.co.uk>
=> Bump OBR version to 0.29.0

galasa-bom/pom.template, release.yaml
=> Bouncy castle upgrade

build-locally.sh, dependency-download/README.md, dependency-download/build.gradle, dependency-download/gradle.properties, dependency-download/settings.gradle, release.yaml, set-version.sh
- set-version doesnt add newlines
- correct bug in script which corrupted release.yaml
- managers component supplies release.yaml information via maven repository
=> mcobbett dependencies via maven repo

release.yaml
Signed-off-by: Eamonn Mansour <47121388+eamansour@users.noreply.github.com>
Needs https://github.com/galasa-dev/wrapping/pull/50 to be merged.
=> Add com.auth0.jwt to OBR

dependency-download/build.gradle, release.yaml, set-version.sh
=> bumping version to 0.31.0

build-locally.sh
In my travels building the code, I wanted to have the galasa-bom update, so could try a change to it out. The build-locally.sh didn't used to re-build the galasa-bom. 
Now it does.
=> build the bom locally also.

dependency-download/build.gradle, release.yaml
Bump development version to 0.35.0.
=> Bump dev version to 0.35.0

dependency-download/build.gradle, release.yaml
See https://github.com/galasa-dev/projectmanagement/issues/1905
=> Bump OBR to 0.36.0

build-locally.sh
This is to ensure that the build-locally works on any operating system and architecture, so that it will build correctly
=> correct the way galasabld is selected and remove duplicate code

dependency-download/build.gradle, release.yaml
For https://github.com/galasa-dev/projectmanagement/issues/1952
=> Bump OBR to 0.37.0

release.yaml
=> Use the new io.grpc bundle from wrapping

build-locally.sh
=> build locally : secrets baseline on linux should not contain a timestamp
