build-locally.sh, javadocs/pom.template
- javadoc site wasnt building. Attempting fix 1.
- build javadoc zip using local build
- Remove debug from javadoc build
The build process was failing in the maven build because not all of the transitive dependency jars were available to the javadoc commmand, so the javadoc tool was failing with 'symbol not found' errors all over the place.
The fix is to pull-down all the dependent jars, unpack them into a `target/classes` folder, and make sure there are no `.java` files in that location.
Next fix was to add the `target/classes` to the `-classpath` in the arguments file that gets built-up for the javadoc tool to use (by the `maven-javadoc-plugin`)
Then when the javadoc tool gets executed, it can resolve any symbols it needs to while rendering the javadoc.
Once that happens, the maven …
=> javadoc site building2

release.yaml
Update needs more investigation as it prevents the felix framework from starting.
=> Revert http jetty update

release.yaml
For https://github.com/galasa-dev/projectmanagement/issues/1089
=> Bump jetty to 5.0.0 and servlet-api to 2.1.0

build-locally.sh, galasa-bom/pom.template, release.yaml
- Developer attribution required in maven. Clashes with IBM normal policy to not publish developer attribution, so was previously removed. Re-added so we can get artifacts published to maven central.
=> re-add developer attribution in galasa bom to satisfy maven central checks.

build-locally.sh
Some debris from a failed attempt at renovating the release.yaml processing was left in the build-locally.sh script.
Corrected it.
=> build-locally.sh pointed to wrong yaml dependencies

build-locally.sh, dependency-download/build.gradle, dependency-download/gradle.properties
- Updating the SOURCE_MAVEN value in the build locally script and gradle properties file to match the remote builds, to pull from the repo before this one in the chain.
=> Updating the value of SOURCE_MAVEN in the builds

build-locally.sh
The local build process was generating a pom.xml in the galasa-bom folder, but was using the wrong option on the build tool, so it ended up not taking notice that the commons-logging package isn't in the obr, but is in the bom.
That explained why it was missing from the bom.
Working in this area as a result of [Local test run to be able to use remote CPS
#1813](https://github.com/galasa-dev/projectmanagement/issues/1813)
=> mcobbett build bom locally

dependency-download/build.gradle, release.yaml
As part of the release process the development version numbers need to be bumped to the next version
=> bumped version to 0.34.0

release.yaml
This change is needed in order to resolve the vulnerabilities within the commons-compress package at version 1.21. to resolve this the package needs to be bumped up to version 1.26.0 along with it's dependencies.
=> bumped version of commons-compress in release.yaml

build-locally.sh
Running the build-locally script was failing to construct the uber OBR pom.xml file due to a typo in the function call (`construct_uber_obr_pom_xmlc` instead of `construct_uber_obr_pom_xml`)
=> Fix syntax error in build-locally

dev.galasa.uber.obr/pom.template, galasa-bom/pom.template
Follow-on from changes in https://github.com/galasa-dev/maven/pull/118
Note: Builds for this PR will fail until the above PR is merged
- Bumped the Galasa maven plugin from 0.17.0 to 0.34.0 in the uber OBR and galasa BOM
=> Bump maven plugin to 0.34.0

release.yaml
For story https://github.com/galasa-dev/projectmanagement/issues/1897
Without upgrading the release.yaml, the changes to the wrapper won't get shipped.
=> Iss1897 - Upgrade version of the JTA wrapper we ship

dependency-download/build.gradle, release.yaml
Bump version of the OBR to 0.34.1 for the patch release.
=> Bump OBR version to 0.34.1

.github/workflows/pr-build.yaml, dockerfiles/dockerfile.javadocmavenrepo, dockerfiles/dockerfile.javadocsite, dockerfiles/dockerfile.obr, dockerfiles/httpdconf/httpd.conf
For issue galasa-dev/projectmanagement#1881
=> Added Build and Pr build github actions workflow 

.github/workflows/build.yaml, .github/workflows/pr-build.yaml
For issue galasa-dev/projectmanagement#1881
=> Added Main build github actions workflow

dependency-download/build.gradle
See https://github.com/galasa-dev/projectmanagement/issues/1652
Fixed build errors when using Gradle 8 in the dependency-download project
=> Add support for Gradle 8

dockerfiles/dockerfile.javadocmavenrepo, dockerfiles/dockerfile.obr
Our namespace in GHCR is galasa-dev not galasadev.
=> Fix dockerfiles paths

.github/workflows/build.yaml, .github/workflows/pr-build.yaml
For the kubectl step , I have used the following methodology
```
- name: Copy files from kubectl image for Galasa boot embedded images
run: |
mkdir -p /opt/k8s/bin
curl -L https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl -o /opt/k8s/bin/kubectl
chmod +x /opt/k8s/bin/kubectl
cp -vr /opt/k8s/bin/kubectl ${{github.workspace}}/obr/dockerfiles/trace-log4j.properties ${{github.workspace}}/obr/obr-generic/
```
`  curl -L https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl -o /opt/k8s/bin/kubectl`
is used in the galasa kubetcl docker image, I have directly used this instead of pulling the docker image, after that the kubectl binary has been copied to the workflow, for further steps.
=> Fixed obr generic jobs

.github/workflows/build.yaml, .github/workflows/pr-build.yaml
Contributes to issue https://github.com/galasa-dev/projectmanagement/issues/1958 - parameterising the build workflow to support any branch/tag.
Removed parameters for when we run the `galasabld` and `argocdcli` images as they will always be from ghcr.io/galasa-dev/xxx:main.
=> Parameterise main build workflow to support any branch/tag

release.yaml
The auth0.jwt bundle was upgraded, so we need to refer to the latest version. 4.4.1
=> Upgrade the dependency on a later wrapped jwt bundle

.github/workflows/build.yaml, .github/workflows/pr-build.yaml
For issue
- galasa-dev/projectmanagement#1967
- galasa-dev/projectmanagement#1963
- galasa-dev/projectmanagement#1964
=> Added test report generation/uploading , fixed java version, added workflow triggers

build-locally.sh
This change on the build build-locally.sh validate the OS where it was called and calls the right galasabld-xxx binary:
buildutils/bin/galasabld-linux-amd64
buildutils/bin/galasabld-windows-amd64
buildutils/bin/galasabld-darwin-amd64
buildutils/bin/galasabld-linux-s390x
buildutils/bin/galasabld-darwin-arm64
Attach testing output:
BUILD SUCCESSFUL in 3s
18 actionable tasks: 18 executed
✔ OK
=> Fixed GALASA_BUILD_TOOL_NAME command based on OS

.github/workflows/build.yaml
As simplatform's build points at the obr's maven repo for its sourceMaven location, it should be rebuilt after the obr, so it can be rebuilt with the latest code and in case there are breaking changes introduced.
=> Add simplatform into build chain

.github/workflows/build.yaml
The integratedtests should be rebuilt after the OBR is so that they have the latest Manager code, and latest galasa-bom to extract the versions from.
=> Build the integratedtests after the OBR

release.yaml
The tests in our suite that use the MVP zipped distribution of Galasa are currently failing. The snakeyaml dependency is not part of the MVP zip and so when these tests attempt to pull the artefact, they have to reach out to Maven Central. At this point, they are getting a timeout and so the test is failing.
This PR adds snakeyaml into the MVP zip so that this failure hopefully doesn't reoccur. Not sure why the timeout when contacting Maven Central is happening, but any MVP tests shouldn't need to contact it anyway.
=> Fixing test failures - Add snakeyaml dependency to MVP
